# file: postgresql/tasks/main.yml

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/main.yml"
  tags: [always]
  
- import_tasks: install.yml
  tags: [postgresql, postgresql-install]
  
- import_tasks: configure.yml
  tags: [postgresql, postgresql-configure]

- import_tasks: users.yml
  tags: [postgresql-users]
  
- import_tasks: tablespace.yml
  tags: [postgresql-tablespace]

- import_tasks: epps.yml
  tags: [postgresql-epps]
  
- import_tasks: efl.yml
  tags: [postgresql-efl]

- import_tasks: webtpt.yml
  tags: [postgresql-webtpt]  

