# file: postgresql/tasks/users.yml

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: "{{ postgresql_service_name }}"
    state: started

- name: PostgreSQL | Ensure tablespace directories exist
  become: true
  file:    
    name: "{{item}}"
    state: directory
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0700
  with_items:
    - "{{tablespace_dir}}"
    - "{{tablespace_dir}}/tbs_data"
    - "{{tablespace_dir}}/tbs_index"
    - "{{tablespace_dir}}/tbs_lob"
