# file: postgresql/tasks/epps.yml

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: "{{ postgresql_service_name }}"
    state: started
   
- name: PostgreSQL | create temp directory to place the script(s)
  become: true
  file:    
    name: "/tmp/ansible/task/webtpt"
    state: directory
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0700

- name: PostgreSQL | webtpt upload SQL query templates
  become: true
  template:
    src: "{{item}}.j2"
    dest: "/tmp/ansible/task/{{item}}"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0700
  with_items:
    - "webtpt/01.create.db.sql"
    
- name: PostgreSQL | create DB
  become: true
  become_user: "{{ postgresql_service_user }}"  
  shell: "{{ postgresql_bin_directory }}/psql -U {{ postgresql_service_user }} -p {{postgresql_port}} -qAtw -f {{item}}"
  args:
    chdir: "/tmp/ansible/task/webtpt"
  with_items:
    - "/tmp/ansible/task/webtpt/01.create.db.sql" 
  register: sql_out
  failed_when: sql_out.stderr != ""
  
- debug: var=sql_out.stderr_lines  
  
