#"Create remote directory Downloads/soffice"
- name: "Creating remote directory Downloads/soffice"
  file:
    path: /home/{{ansible_user}}/Downloads/soffice
    state: directory
    recurse: yes

#Download locally openoffice
- name: "Downloading openoffice"
  get_url:
   url: "{{soffice.mirror}}/{{soffice.version}}/binaries/en-US/Apache_OpenOffice_{{soffice.version}}_{{soffice.release}}.tar.gz"
   dest: ~/Downloads/soffice.tar.gz
  run_once: true
  delegate_to: localhost

#Copy the downloaded file to the remote machine
- name: "Remote copy to server"
  copy:
    src: ~/Downloads/soffice.tar.gz
    dest: /home/{{ansible_user}}/Downloads/soffice.tar.gz
    mode: 0777

#Unpackage the openoffice tar.gz
- name: "Unpackaging soffice"
  unarchive:
    src: /home/{{ansible_user}}/Downloads/soffice.tar.gz
    dest: /home/{{ansible_user}}/Downloads/soffice
    creates: /home/{{ansible_user}}/Downloads/soffice/en-US/RPMS
    remote_src: yes 


# Get a list of openoffice rpms from the RPMs directory
- name: Finding openoffice rpm files and register the result 
  find:
    paths: /home/{{ansible_user}}/Downloads/soffice/en-US/RPMS
    patterns: "*.rpm"
  register: soffice_rpm_files

# Create a list of the soffice rpms to use with the yum install command
- set_fact:
    rpm_list: "{{ soffice_rpm_files.files | map(attribute='path') | list}}"

# Use yum to install soffice RPMs list
- name: Installing openoffice rpm files using rpm_list
  become: true
  yum:
    name: "{{rpm_list}}"
    state: installed

# Copying soffice.service template file
- name: "Copying soffice.service template"
  become: yes
  template:
    src: soffice.service.j2
    dest: /etc/systemd/system/soffice.service
    backup: yes
    mode: 0660

#enable the openoffice service
- name: "Enabling and start soffice.service"
  become: yes
  systemd: 
    name: soffice.service
    enabled: yes
    daemon_reload: yes
    state: restarted
    force: yes
