---
- name: "Creating local directory for downloading artifacts"
  hosts: localhost
  tasks:
    - name: "Creating local directory ~/Downloads"
      file:
        path: ~/Downloads/soffice
        state: directory
        recurse: yes

- name: "Starting installation"
  hosts: "{{target_host}}"
  vars_files:
    - "./vars/{{target_env}}.yml"
  roles:  
  - basic
  - msfonts
  - soffice
  - clamav

